### ISSUE TITLE
Error in Node using require

### ISSUE THREAD

**Issue by puzzit** [jeanlescure/short-unique-id#28]
Could not find a declaration file for module 'short-unique-id'

**Comment by jeanlescure** [comment]
Hi @abram14 , please provide more information using the following template:

## Expected Behavior

[screenshot, logs, or example]

## Current Behavior

[screenshot, logs, or example]

## Steps to Reproduce

1.
2.
3.

## Context (Environment)

[OS including version (i.e. Mac OSX Catalina 10.15.3)]
[Javascript runtime including version (i.e. Node v13.13)]
[Any other relevant notes regarding the context in which the issue is experienced
(i.e. using TypeScript or Babel)]

## Detailed Description

Provide a detailed description about the issue at hand

**Comment by puzzit** [comment]
Hi @jeanlescure, unable to reproduce, I was trying to use it in a firebase cloud function and initiated a project using firebase command line tools, may be some problem with firebase cli tools. I started a fresh project using npm init and it worked without any issue.
