### ISSUE TITLE
Formalized Specification

### ISSUE THREAD

**Issue by HeathNaylor** [jeanlescure/short-unique-id#40]
Hey, this library looks really promising. What would you think of collaborating on creating a formalized specification that can be used to code libraries in different languages to? I'd love to port this over to C++, PHP, Java, etc. but I don't want the libraries to be "incompatible" with each other over time.

**Comment by jeanlescure** [comment]
Hi @HeathNaylor ,

First of all, you are definitely welcome to collaborate with us, specially since you have hit the nail in the head! 😄 

One of these days I had commented on [an unrelated issue](https://github.com/jeanlescure/short-unique-id/issues/31#issuecomment-741844299) that we are working on version 4.

The conversation has precisely revolved around the fact of porting the code either to C, C++, or Rust, so that we can then deploy to all other languages as interfaces using the resulting native module.

And just to share some key points, we were originally gravitating toward Rust since it's pretty simple to compile to WebAssembly, but then a quick search turned up [MDN's entry regarding compiling C/C++ to WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm) which makes it look like a pretty trivial task. So now the only other compelling argument to use Rust instead of C/C++ is avoiding any safety concerns in regards to memory overflow attacks since Rust's intellisense and compiler are much more pedantic precisely in those regards right out of the box.

Coming back to the original subject, I am currently working on formal specs for version 4. Once the initial draft is ready I'll create an issue where we can discuss further details into collaboration.

With that said, I'd love to read any feedback you may have about the aforementioned C/C++ vs Rust debate.

Cheers

**Comment by jeanlescure** [comment]
For the record, we have settled on using Rust.

I'm keeping this issue open until I open the official v4 roadmap issue.
