### ISSUE TITLE
The homepage Deno example fails to run

### ISSUE THREAD

**Issue by mybuddymichael** [jeanlescure/short-unique-id#47]
Attempting to run this simple example from the homepage fails:

```javascript
import ShortUniqueId from 'https://cdn.jsdelivr.net/npm/short-unique-id@latest/src/index.ts';

const uid = new ShortUniqueId();

console.log(uid)
```

Deno complains:
```
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://cdn.jsdelivr.net/npm/short-unique-id@latest/package.json
  MediaType: Json
```

It appears that [Deno does not yet support JSON modules](https://github.com/denoland/deno/issues/7623).

**Comment by mybuddymichael** [comment]
I just instead used `import ShortUniqueId from 'https://esm.sh/short-unique-id';` (per Deno's docs on imports) and that worked fine.

**Comment by jeanlescure** [comment]
I've gone ahead and updated the docs on [this](https://github.com/jeanlescure/short-unique-id/commit/3d9b8efe87bb690febd14af9f47f3eb0732df834#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and [this other](https://github.com/jeanlescure/short-unique-id/commit/5bf27fc3d923cd08a0c1f973b8ee88e033ced469#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) commit.

Also published a release in order to update npm and the website docs.

Cheers for the contribution @mybuddymichael 🚀
